import type { BotConfig, BotSettingsState, ActivityItem, PerformanceMetrics } from "./types"

export const botConfigs: BotConfig[] = [
  {
    id: "bot-1",
    name: "AI Momentum Trader",
    type: "ai",
    icon: "🤖",
    status: "active",
    exchange: "binance",
    pair: "BTC/USDT",
    strategy: "momentum",
    profitability: 12.5,
    lastRun: "2 minutes ago",
    description: "AI-powered momentum trading bot with advanced market analysis",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-20T14:22:00Z",
    totalTrades: 156,
    winRate: 68.5,
    balance: 15420.5,
  },
  {
    id: "bot-2",
    name: "DCA Accumulator",
    type: "dca",
    icon: "📈",
    status: "active",
    exchange: "coinbase",
    pair: "ETH/USD",
    strategy: "dca",
    profitability: 8.3,
    lastRun: "5 minutes ago",
    description: "Dollar-cost averaging bot for steady accumulation",
    createdAt: "2024-01-10T09:15:00Z",
    updatedAt: "2024-01-20T13:45:00Z",
    totalTrades: 89,
    winRate: 72.1,
    balance: 8950.25,
  },
  {
    id: "bot-3",
    name: "Signal Follower Pro",
    type: "signal",
    icon: "📡",
    status: "paused",
    exchange: "bybit",
    pair: "SOL/USDT",
    strategy: "signal",
    profitability: -2.1,
    lastRun: "1 hour ago",
    description: "Professional signal following bot with risk management",
    createdAt: "2024-01-12T16:20:00Z",
    updatedAt: "2024-01-19T11:30:00Z",
    totalTrades: 45,
    winRate: 55.6,
    balance: 4890.75,
  },
  {
    id: "bot-4",
    name: "Arbitrage Hunter",
    type: "arbitrage",
    icon: "⚡",
    status: "active",
    exchange: "kraken",
    pair: "BTC/EUR",
    strategy: "arbitrage",
    profitability: 15.7,
    lastRun: "30 seconds ago",
    description: "Cross-exchange arbitrage opportunities hunter",
    createdAt: "2024-01-08T12:45:00Z",
    updatedAt: "2024-01-20T14:55:00Z",
    totalTrades: 234,
    winRate: 89.3,
    balance: 12750.8,
  },
  {
    id: "bot-5",
    name: "Grid Master",
    type: "grid",
    icon: "🔲",
    status: "inactive",
    exchange: "okx",
    pair: "ADA/USDT",
    strategy: "grid",
    profitability: 5.9,
    lastRun: "2 days ago",
    description: "Grid trading bot for sideways market conditions",
    createdAt: "2024-01-05T08:30:00Z",
    updatedAt: "2024-01-18T16:20:00Z",
    totalTrades: 67,
    winRate: 64.2,
    balance: 3250.4,
  },
]

export const defaultBotSettings: BotSettingsState = {
  selectedBot: "bot-1",
  searchQuery: "",
  showApiKey: false,
  riskLevel: "medium",
  timeframe: "1h",
  strategy: "momentum",
  exchange: "binance",
  tradingPair: "BTC/USDT",
  maxPositionSize: 10,
  stopLossPercentage: 5,
  takeProfitPercentage: 15,
  trailingStopLoss: false,
  trailingTakeProfit: false,
  aiAssistance: true,
  autoRebalance: false,
  notificationsEnabled: true,
  telegramNotifications: false,
  emailNotifications: true,
  pushNotifications: true,
  botName: "AI Momentum Trader",
  botType: "ai",
  apiKey: "",
  apiSecret: "",
  autoStart: false,
  // Strategy parameters
  rsiPeriod: 14,
  rsiOverbought: 70,
  rsiOversold: 30,
  macdFast: 12,
  macdSlow: 26,
  macdSignal: 9,
  bollingerPeriod: 20,
  bollingerStd: 2,
  meanLookback: 50,
  dcaInterval: "1d",
  dcaAmount: 100,
  dcaDynamic: true,
  customStrategyJson: "",
  // Risk management
  minPositionSize: 10,
  minPositionCurrency: "USD",
  maxOpenPositions: 5,
  maxDrawdown: 20,
  // Advanced settings
  executionMode: "live",
  orderType: "market",
  slippageTolerance: 0.5,
  retryAttempts: 3,
  executionSchedule: "continuous",
  debugMode: false,
  testMode: false,
}

export const mockActivityItems: ActivityItem[] = [
  {
    id: "activity-1",
    type: "buy",
    title: "Buy Order Executed",
    description: "Purchased 0.1 BTC at $42,500",
    timestamp: "2 minutes ago",
    icon: "📈",
    color: "green",
  },
  {
    id: "activity-2",
    type: "signal",
    title: "Signal Received",
    description: "Strong buy signal for ETH/USDT",
    timestamp: "5 minutes ago",
    icon: "📡",
    color: "blue",
  },
  {
    id: "activity-3",
    type: "sell",
    title: "Sell Order Executed",
    description: "Sold 2.5 ETH at $2,650",
    timestamp: "12 minutes ago",
    icon: "📉",
    color: "red",
  },
  {
    id: "activity-4",
    type: "update",
    title: "Strategy Updated",
    description: "RSI parameters adjusted for better performance",
    timestamp: "1 hour ago",
    icon: "⚙️",
    color: "yellow",
  },
  {
    id: "activity-5",
    type: "start",
    title: "Bot Started",
    description: "AI Momentum Trader activated",
    timestamp: "2 hours ago",
    icon: "▶️",
    color: "green",
  },
]

export const mockPerformanceMetrics: PerformanceMetrics = {
  totalProfit: 2450.75,
  totalProfitPercentage: 12.25,
  winRate: 68.5,
  totalTrades: 156,
  winningTrades: 107,
  avgProfit: 85.3,
  avgLoss: -42.15,
  profitFactor: 2.02,
  maxDrawdown: 8.5,
  sharpeRatio: 1.85,
  avgTradeDuration: "4h 32m",
}
