import type { MarketSummaryItem, PerformanceData, SignalBot, SignalProvider, Trader } from "./types"

// Performance data for the chart
export const performanceData: PerformanceData[] = [
  { date: "Jan", profit: 2400, trades: 45, winRate: 68 },
  { date: "Feb", profit: 1398, trades: 52, winRate: 72 },
  { date: "Mar", profit: 9800, trades: 38, winRate: 65 },
  { date: "Apr", profit: 3908, trades: 61, winRate: 78 },
  { date: "May", profit: 4800, trades: 49, winRate: 71 },
  { date: "Jun", profit: 3800, trades: 55, winRate: 74 },
  { date: "Jul", profit: 4300, trades: 47, winRate: 69 },
  { date: "Aug", profit: 5200, trades: 58, winRate: 76 },
  { date: "Sep", profit: 6100, trades: 62, winRate: 79 },
  { date: "Oct", profit: 7200, trades: 54, winRate: 73 },
  { date: "Nov", profit: 8100, trades: 59, winRate: 77 },
  { date: "Dec", profit: 9200, trades: 65, winRate: 81 },
]

// Market summary data
export const marketSummaryData: MarketSummaryItem[] = [
  { market: "BTC/USDT", price: "$42,830", change: "+2.4%", isPositive: true },
  { market: "ETH/USDT", price: "$3,890", change: "-0.8%", isPositive: false },
  { market: "SOL/USDT", price: "$106", change: "+5.2%", isPositive: true },
  { market: "BNB/USDT", price: "$580", change: "+1.3%", isPositive: true },
]

// Signal Bots data
export const signalBots: SignalBot[] = [
  {
    id: 1,
    name: "BTC Trend Follower",
    status: "Active",
    trades: 145,
    winRate: 68,
    profit: 2340.5,
    profitPercent: 12.4,
    volume: 45600,
    timeframe: "1D",
  },
  {
    id: 2,
    name: "ETH Scalper",
    status: "Active",
    trades: 287,
    winRate: 72,
    profit: 1870.25,
    profitPercent: 9.8,
    volume: 32400,
    timeframe: "4H",
  },
  {
    id: 3,
    name: "SOL Breakout",
    status: "Paused",
    trades: 98,
    winRate: 65,
    profit: 980.75,
    profitPercent: 7.2,
    volume: 18900,
    timeframe: "1H",
  },
  {
    id: 4,
    name: "BNB Swing",
    status: "Active",
    trades: 76,
    winRate: 59,
    profit: -340.2,
    profitPercent: -2.1,
    volume: 12500,
    timeframe: "1D",
  },
  {
    id: 5,
    name: "AVAX Momentum",
    status: "Stopped",
    trades: 42,
    winRate: 48,
    profit: -520.8,
    profitPercent: -4.5,
    volume: 8700,
    timeframe: "4H",
  },
]

// Traders data
export const traders: Trader[] = [
  {
    id: 1,
    name: "CryptoMaster",
    status: "Active",
    followers: 1245,
    winRate: 78,
    profit: 12340.5,
    profitPercent: 32.4,
    volume: 245600,
    timeframe: "All Time",
  },
  {
    id: 2,
    name: "BTCWhale",
    status: "Active",
    followers: 987,
    winRate: 72,
    profit: 8970.25,
    profitPercent: 24.8,
    volume: 132400,
    timeframe: "All Time",
  },
  {
    id: 3,
    name: "AltcoinHunter",
    status: "Paused",
    followers: 645,
    winRate: 65,
    profit: 4980.75,
    profitPercent: 17.2,
    volume: 78900,
    timeframe: "All Time",
  },
  {
    id: 4,
    name: "TradingPro",
    status: "Active",
    followers: 432,
    winRate: 59,
    profit: 2340.2,
    profitPercent: 12.1,
    volume: 52500,
    timeframe: "All Time",
  },
  {
    id: 5,
    name: "CryptoNewbie",
    status: "Stopped",
    followers: 123,
    winRate: 48,
    profit: -520.8,
    profitPercent: -4.5,
    volume: 18700,
    timeframe: "All Time",
  },
]

// Signal Providers data
export const signalProviders: SignalProvider[] = [
  {
    id: 1,
    name: "Alpha Signals",
    status: "Active",
    subscribers: 2450,
    winRate: 82,
    profit: 18340.5,
    profitPercent: 42.4,
    signals: 345,
    timeframe: "All Time",
  },
  {
    id: 2,
    name: "Crypto Insights",
    status: "Active",
    subscribers: 1870,
    winRate: 76,
    profit: 12970.25,
    profitPercent: 34.8,
    signals: 287,
    timeframe: "All Time",
  },
  {
    id: 3,
    name: "Moon Shots",
    status: "Paused",
    subscribers: 980,
    winRate: 62,
    profit: 6980.75,
    profitPercent: 21.2,
    signals: 156,
    timeframe: "All Time",
  },
  {
    id: 4,
    name: "Whale Alerts",
    status: "Active",
    subscribers: 765,
    winRate: 68,
    profit: 5340.2,
    profitPercent: 18.1,
    signals: 124,
    timeframe: "All Time",
  },
  {
    id: 5,
    name: "DeFi Signals",
    status: "Stopped",
    subscribers: 320,
    winRate: 52,
    profit: 1520.8,
    profitPercent: 8.5,
    signals: 87,
    timeframe: "All Time",
  },
]
